### PR TITLE
Timeline, Hero section updates

### PR DESCRIPTION
**Pull request by akash0708**

### CODE REVIEW

**Comment by roytanmay** [comment]
There is a conflict in the src/app/page.js file. Please resolve the conflict then create your PR @akash0708 @KushajM

**Comment by akash0708** [comment]
Resolved

**Comment by akash0708** [comment]
Campus Ambassador Page added in a new route assessible at `/ambassador`

**Comment by akash0708** [comment]
@roytanmay Hero section improved, timeline and campus ambassador page added.

image
image
image

**Pull request merged**
